### ISSUE TITLE
Incompatible runner GNU Make

### ISSUE THREAD

**Issue by philenz** [VladRassokhin/CMake-runner-plugin#4]
Even though my agent definitely has GNU make installed in /bin/make, the GNU Make build runner is not listed as a build runner for the agent.

So any build using GNU Make build runner is unable to find any compatible agent.

CMake build and configure are both listed as build runners for my agent.
CMake is installed in /bin/cmake

OS is RedHat Server 7.1 running on AWS.
Team City version 9.1.3.

**Comment by VladRassokhin** [comment]
Please try [latest version of plugin](https://teamcity.jetbrains.com/gueshAuth/repository/download/bt347/528932:id/cmake-runner.zip) and attach/gist teamcity-agent.log here.

**Comment by philenz** [comment]
Thank you.. that works great :-)

I just downloaded the (old) zip file from the link on https://confluence.jetbrains.com/display/TW/CMake+Plugin

I should've built from source.

Anyway, again, thanks a lot.
