### ISSUE TITLE
Teamcity 2017.1.2 no compatible agents

### ISSUE THREAD

**Issue by sascha-andres** [VladRassokhin/CMake-runner-plugin#5]
Hi,

I have make installed on my build agent still the agent is listed as incompatible:

    Incompatible runner: GNU Make

I restarted the agent and it did not work. What do I need to do to get it running on my agent?

Kind regards,
Sascha

**Comment by VladRassokhin** [comment]
Please publish agent logs on gist and provide link here or send them to me by email.

**Comment by juanalday** [comment]
Having the same problem since upgrading to 2017.1.4
https://gist.github.com/juanalday/9a2fd85e4955cffd4e775de7e33f908b
