### ISSUE TITLE
Teamcity 2017.1.4 incompatibility

### ISSUE THREAD

**Issue by juanalday** [VladRassokhin/CMake-runner-plugin#6]
After upgrading from 2017.1.3 to 2017.1.4, the cmake plugin has stopped working
This affects servers/agents running in Windows/Linux

cmake-runner (ver:10.0-2)

Attached is a gist with a log from an agent
https://gist.github.com/juanalday/9a2fd85e4955cffd4e775de7e33f908b

**Comment by VladRassokhin** [comment]
Hi, there was changes in TeamCity API, please try [the new version of plugin](https://teamcity.jetbrains.com/guestAuth/repository/download/TeamCityPluginsByJetBrains_CMakePlugin_BuildAgainstTeamCity100x/.lastSuccessful/cmake-runner.zip).
